/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

// x-bows knight vial uid
#define VIAL_KEYBOARD_UID {0xA0, 0x52, 0x04, 0xCE, 0x23, 0x45, 0x71, 0x6D}

// esc and enter
#define VIAL_UNLOCK_COMBO_ROWS {0, 3}
#define VIAL_UNLOCK_COMBO_COLS {0, 13}

// all egb animation
#undef RGB_MATRIX_STARTUP_MODE // Sets the default mode, if none has been set
#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BAND_SAT
#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#undef ENABLE_RGB_MATRIX_RAINDROPS
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN

#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN

#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef ENABLE_RGB_MATRIX_SPLASH
#undef ENABLE_RGB_MATRIX_MULTISPLASH
#undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

/* #define ENABLE_RGB_MATRIX_ALPHAS_MODS */
/* #define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN */
/* #define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT */
/* #define ENABLE_RGB_MATRIX_BREATHING */
/* #define ENABLE_RGB_MATRIX_BAND_SAT */
/* #define ENABLE_RGB_MATRIX_BAND_VAL */
/* #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT */
/* #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL */
/* #define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT */
/* #define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL */
/* #define ENABLE_RGB_MATRIX_CYCLE_ALL */
/* #define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT */
/* #define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN */
/* #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON */
/* #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN */
/* #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL */
/* #define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL */
/* #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL */
/* #define ENABLE_RGB_MATRIX_DUAL_BEACON */
/* #define ENABLE_RGB_MATRIX_RAINBOW_BEACON */
/* #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS */
/* #define ENABLE_RGB_MATRIX_RAINDROPS */
/* #define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS */
/* #define ENABLE_RGB_MATRIX_HUE_BREATHING */
/* #define ENABLE_RGB_MATRIX_HUE_PENDULUM */
/* #define ENABLE_RGB_MATRIX_HUE_WAVE */
/* #define ENABLE_RGB_MATRIX_PIXEL_FRACTAL */
/* #define ENABLE_RGB_MATRIX_PIXEL_FLOW */
/* #define ENABLE_RGB_MATRIX_PIXEL_RAIN */

/* #define ENABLE_RGB_MATRIX_TYPING_HEATMAP */
/* #define ENABLE_RGB_MATRIX_DIGITAL_RAIN */


/* #define RGB_MATRIX_FRAMEBUFFER_EFFECTS */

/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS */
/* #define ENABLE_RGB_MATRIX_SPLASH */
/* #define ENABLE_RGB_MATRIX_MULTISPLASH */
/* #define ENABLE_RGB_MATRIX_SOLID_SPLASH */
/* #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH */


#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_REACTIVE // Sets the default mode, if none has been set
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT    // Full gradient scrolling left to right
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN       // Full gradient scrolling top to bottom
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE          // Static single hue, pulses keys hit to shifted hue then fades to current hue

/* #define ENABLE_RGB_MATRIX_BREATHING           // Single hue brightness cycling animation */
